doctrine:
    orm:
        auto_generate_proxy_classes: false
        metadata_cache_driver:
            type: service
            pool: redis_cache_service
        query_cache_driver:
            type: service
            pool: redis_cache_service
        result_cache_driver:
            type: service
            pool: redis_cache_service

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
